import { type ArgumentMetadata, Injectable, type PipeTransform } from '@nestjs/common';
import { ApiBody } from '@nestjs/swagger';
import { applyDecorators } from '@nestjs/common';
import { z, type ZodType } from 'zod';

/** Validates and parses a request part with a shared contract schema (backend is authoritative). */
@Injectable()
export class ZodPipe<T extends ZodType> implements PipeTransform<unknown, z.infer<T>> {
  constructor(private readonly schema: T) {}

  transform(value: unknown, _metadata: ArgumentMetadata): z.infer<T> {
    return this.schema.parse(value);
  }
}

export function zod<T extends ZodType>(schema: T): ZodPipe<T> {
  return new ZodPipe(schema);
}

/** Documents a zod body schema in OpenAPI (JSON Schema generated by zod itself). */
export function ApiZodBody(schema: ZodType): MethodDecorator {
  let jsonSchema: Record<string, unknown>;
  try {
    jsonSchema = z.toJSONSchema(schema, { io: 'input', unrepresentable: 'any' }) as Record<string, unknown>;
  } catch {
    jsonSchema = { type: 'object' };
  }
  delete jsonSchema.$schema;
  return applyDecorators(ApiBody({ schema: jsonSchema }));
}
